<a href="https://colab.research.google.com/github/arsha-k-k/Crop-Yield-Prediction-Using-Machine-Learning/blob/main/Crop_Yield.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv("/content/drive/MyDrive/PROJECT/ML Crop Yield Prediction/crop_yield.csv")
data

Region Soil_Type     Crop  Rainfall_mm  Temperature_Celsius  \
0        West     Sandy   Cotton   897.077239            27.676966   
1       South      Clay     Rice   992.673282            18.026142   
2       North      Loam   Barley   147.998025            29.794042   
3       North     Sandy  Soybean   986.866331            16.644190   
4       South      Silt    Wheat   730.379174            31.620687   
...       ...       ...      ...          ...                  ...   
999995   West      Silt     Rice   302.805345            27.987428   
999996  South    Chalky   Barley   932.991383            39.661039   
999997  North     Peaty   Cotton   867.362046            24.370042   
999998   West      Silt    Wheat   492.812857            33.045505   
999999   West     Sandy    Maize   180.936180            27.298847   

        Fertilizer_Used  Irrigation_Used Weather_Condition  Days_to_Harvest  \
0                 False             True            Cloudy              122   
1                  True             True             Rainy              140   
2                 False            False             Sunny              106   
3                 False             True             Rainy              146   
4                  True             True            Cloudy              110   
...                 ...              ...               ...              ...   
999995            False            False             Sunny               76   
999996             True            False             Rainy               93   
999997             True            False            Cloudy              108   
999998            False            False             Sunny              102   
999999             True            False             Sunny               76   

        Yield_tons_per_hectare  
0                     6.555816  
1                     8.527341  
2                     1.127443  
3                     6.517573  
4                     7.248251  
...                        ...  
999995                1.347586  
999996                7.311594  
999997                5.763182  
999998                2.070159  
999999                2.937243  

[1000000 rows x 10 columns]

In [ ]:
data.head()

Region Soil_Type     Crop  Rainfall_mm  Temperature_Celsius  \
0   West     Sandy   Cotton   897.077239            27.676966   
1  South      Clay     Rice   992.673282            18.026142   
2  North      Loam   Barley   147.998025            29.794042   
3  North     Sandy  Soybean   986.866331            16.644190   
4  South      Silt    Wheat   730.379174            31.620687   

   Fertilizer_Used  Irrigation_Used Weather_Condition  Days_to_Harvest  \
0            False             True            Cloudy              122   
1             True             True             Rainy              140   
2            False            False             Sunny              106   
3            False             True             Rainy              146   
4             True             True            Cloudy              110   

   Yield_tons_per_hectare  
0                6.555816  
1                8.527341  
2                1.127443  
3                6.517573  
4                7.248251

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 10 columns):
 #   Column                  Non-Null Count    Dtype  
---  ------                  --------------    -----  
 0   Region                  1000000 non-null  object 
 1   Soil_Type               1000000 non-null  object 
 2   Crop                    1000000 non-null  object 
 3   Rainfall_mm             1000000 non-null  float64
 4   Temperature_Celsius     1000000 non-null  float64
 5   Fertilizer_Used         1000000 non-null  bool   
 6   Irrigation_Used         1000000 non-null  bool   
 7   Weather_Condition       1000000 non-null  object 
 8   Days_to_Harvest         1000000 non-null  int64  
 9   Yield_tons_per_hectare  1000000 non-null  float64
dtypes: bool(2), float64(3), int64(1), object(4)
memory usage: 62.9+ MB


In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
data.shape

(1000000, 10)

In [ ]:
data.ndim

2

In [ ]:
data.describe()

Rainfall_mm  Temperature_Celsius  Days_to_Harvest  \
count  1000000.000000       1000000.000000   1000000.000000   
mean       549.981901            27.504965       104.495025   
std        259.851320             7.220608        25.953412   
min        100.000896            15.000034        60.000000   
25%        324.891090            21.254502        82.000000   
50%        550.124061            27.507365       104.000000   
75%        774.738520            33.753267       127.000000   
max        999.998098            39.999997       149.000000   

       Yield_tons_per_hectare  
count          1000000.000000  
mean                 4.649472  
std                  1.696572  
min                 -1.147613  
25%                  3.417637  
50%                  4.651808  
75%                  5.879200  
max                  9.963372

In [ ]:
data.isna().any()

Region                    False
Soil_Type                 False
Crop                      False
Rainfall_mm               False
Temperature_Celsius       False
Fertilizer_Used           False
Irrigation_Used           False
Weather_Condition         False
Days_to_Harvest           False
Yield_tons_per_hectare    False
dtype: bool

In [ ]:
data.isna().sum()

Region                    0
Soil_Type                 0
Crop                      0
Rainfall_mm               0
Temperature_Celsius       0
Fertilizer_Used           0
Irrigation_Used           0
Weather_Condition         0
Days_to_Harvest           0
Yield_tons_per_hectare    0
dtype: int64

In [ ]:
data.columns

Index(['Region', 'Soil_Type', 'Crop', 'Rainfall_mm', 'Temperature_Celsius',
       'Fertilizer_Used', 'Irrigation_Used', 'Weather_Condition',
       'Days_to_Harvest', 'Yield_tons_per_hectare'],
      dtype='object')

In [ ]:
data['Crop'].value_counts()

Crop
Maize      166824
Rice       166792
Barley     166777
Wheat      166673
Cotton     166585
Soybean    166349
Name: count, dtype: int64

In [ ]:
data['Region'].value_counts()

Region
North    250173
West     250074
South    250054
East     249699
Name: count, dtype: int64

In [ ]:
data['Soil_Type'].value_counts()

Soil_Type
Sandy     167119
Loam      166795
Chalky    166779
Silt      166672
Clay      166352
Peaty     166283
Name: count, dtype: int64

In [ ]:
data['Weather_Condition'].value_counts()

Weather_Condition
Sunny     333790
Rainy     333561
Cloudy    332649
Name: count, dtype: int64

In [ ]:
# Replacing categorical values for 'Crop', 'Region', 'Soil_Type', etc.
data.replace({'Crop': {'Maize': 0, 'Rice': 1, 'Barley': 2, 'Wheat': 3, 'Cotton': 4, 'Soybean': 5}}, inplace=True)

data.replace({'Region': {'North': 0, 'West': 1, 'South': 2, 'East': 3}}, inplace=True)

data.replace({'Soil_Type': {'Sandy': 0, 'Loam': 1, 'Chalky': 2, 'Silt': 3, 'Clay': 4, 'Peaty': 5}}, inplace=True)

data.replace({'Weather_Condition': {'Sunny': 0, 'Rainy': 1, 'Cloudy': 2}}, inplace=True)

# Replace booleans (True/False) with integers (1/0)
data.replace({'Fertilizer_Used': {False: 0, True: 1}}, inplace=True)

data.replace({'Irrigation_Used': {False: 0, True: 1}}, inplace=True)


<ipython-input-18-3c2e69799fff>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.replace({'Crop': {'Maize': 0, 'Rice': 1, 'Barley': 2, 'Wheat': 3, 'Cotton': 4, 'Soybean': 5}}, inplace=True)
<ipython-input-18-3c2e69799fff>:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.replace({'Region': {'North': 0, 'West': 1, 'South': 2, 'East': 3}}, inplace=True)
<ipython-input-18-3c2e69799fff>:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explic

In [ ]:
print(data.head())

   Region  Soil_Type  Crop  Rainfall_mm  Temperature_Celsius  Fertilizer_Used  \
0       1          0     4   897.077239            27.676966                0   
1       2          4     1   992.673282            18.026142                1   
2       0          1     2   147.998025            29.794042                0   
3       0          0     5   986.866331            16.644190                0   
4       2          3     3   730.379174            31.620687                1   

   Irrigation_Used  Weather_Condition  Days_to_Harvest  Yield_tons_per_hectare  
0                1                  2              122                6.555816  
1                1                  1              140                8.527341  
2                0                  0              106                1.127443  
3                1                  1              146                6.517573  
4                1                  2              110                7.248251  


In [ ]:
x=data.drop(columns='Yield_tons_per_hectare',axis=1)
x.head()

Region  Soil_Type  Crop  Rainfall_mm  Temperature_Celsius  Fertilizer_Used  \
0       1          0     4   897.077239            27.676966                0   
1       2          4     1   992.673282            18.026142                1   
2       0          1     2   147.998025            29.794042                0   
3       0          0     5   986.866331            16.644190                0   
4       2          3     3   730.379174            31.620687                1   

   Irrigation_Used  Weather_Condition  Days_to_Harvest  
0                1                  2              122  
1                1                  1              140  
2                0                  0              106  
3                1                  1              146  
4                1                  2              110

In [ ]:
y=data['Yield_tons_per_hectare']
y.head()

0    6.555816
1    8.527341
2    1.127443
3    6.517573
4    7.248251
Name: Yield_tons_per_hectare, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=2,test_size=0.2)

In [ ]:
print(x.shape,xtrain.shape,xtest.shape)

(1000000, 9) (800000, 9) (200000, 9)


Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
from sklearn.metrics import r2_score
from sklearn import metrics

In [ ]:
regressor = LinearRegression()
regressor.fit(xtrain,ytrain)

LinearRegression()

In [ ]:
training_data_prediction = regressor.predict(xtrain)

In [ ]:
r2_train = metrics.r2_score(ytrain, training_data_prediction)
print(r2_train)

0.9130512117430872


In [ ]:
test_data_prediction = regressor.predict(xtest)

In [ ]:
r2_test = metrics.r2_score(ytest, test_data_prediction)
print(r2_train)

0.9130512117430872


In [ ]:
ypred=regressor.predict(xtest)
ypred

array([2.88294445, 6.76812024, 7.52895967, ..., 3.31288276, 4.15683101,
       4.71850204])

In [ ]:
score=r2_score(ytest,ypred)
score

0.9126850706344329

KNN

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor()
knn.fit(xtrain,ytrain)

KNeighborsRegressor()

In [ ]:
ypred=knn.predict(xtest)
ypred

array([3.22119609, 6.77141173, 5.73971764, ..., 3.0374358 , 4.65620223,
       3.0389219 ])

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
score=r2_score(ytest,ypred)
score

0.598020804816563

Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeRegressor
DT=DecisionTreeRegressor()
DT.fit(xtrain,ytrain)

DecisionTreeRegressor()

In [ ]:
ypred=DT.predict(xtest)
ypred

array([2.15115221, 6.52917393, 7.04572434, ..., 2.79077243, 2.85561346,
       4.72811355])

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
score=r2_score(ytest,ypred)
score

0.8151428477374972

Random Forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rfc = RandomForestRegressor(n_estimators=20, criterion='squared_error', max_depth=5, max_features=5)
# help(rfc)
rfc.fit(xtrain,ytrain)

RandomForestRegressor(max_depth=5, max_features=5, n_estimators=20)

In [ ]:
ypred=rfc.predict(xtest)
ypred

array([3.14897867, 6.60707288, 7.47267054, ..., 3.40206233, 3.98612926,
       4.59368916])

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
print('Accuracy score :',r2_score(ytest,ypred))

Accuracy score : 0.8829393380576542


XG Boost

In [ ]:
from xgboost import XGBRegressor
xgbr=XGBRegressor()
xgbr.fit(xtrain,ytrain)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [ ]:
ypred=xgbr.predict(xtest)
ypred

array([2.8649437, 6.7336106, 7.5514393, ..., 3.369058 , 4.153721 ,
       4.7160664], dtype=float32)

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(ytest,ypred)

0.9121400980324534

Model Prediction

In [ ]:
import numpy as np

In [ ]:
input_data = (3,4,5,349.8723286873743,17.036669909305164,1,0,2,100)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
prediction = DT.predict(input_data_reshaped)
print(prediction)

[3.03384818]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


In [ ]:
import joblib
with open("crop yield.joblib", 'wb') as f:
    joblib.dump(DT, f)

In [ ]:
import joblib

joblib.dump(data, 'transformed_data.joblib')

print("Transformed data saved successfully to 'transformed_data.joblib'.")

Transformed data saved successfully to 'transformed_data.joblib'.
